<?php
/**
 * @file db_structure.php
 * Файл со структурой базы данных модуля рассылок
 *
 * Создан 16.09.2011
 *
 * @author Konstantin Kuznetsov <lopikun@gmail.com>, blade39 <blade39@kolosstudio.ru>
 * @version 2.6
 */
/*Обязательно вставляем во все файлы для защиты от взлома*/
if( !defined('KS_ENGINE') ) {die("Hacking attempt!");}

$arStructure=array(
	'subscribe_newsletters'=>array(
		'id' => array(
			'Field'	=>	'id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'PRI',
			'Default'=>	'0',
			'Extra'	=>	'auto_increment',
		),
		'name'=>array(
			'Field'=>'name',
			'Type'=>'char(255)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'description'=>array(
			'Field'=>'description',
			'Type'=>'char(255)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'send_type'=>array(
			'Field'=>'send_type',
			'Type'=>'tinyint(1)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'0',
			'Extra'=>'',
		),
		'active'=>array(
			'Field'=>'active',
			'Type'=>'tinyint(1)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'0',
			'Extra'=>'',
		),
		'date_add' => array(
			'Field'	=>	'date_add',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
	),
	'subscribe_releases'=>array(
		'id' => array(
			'Field'	=>	'id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'PRI',
			'Default'=>	'0',
			'Extra'	=>	'auto_increment',
		),
		'theme'=>array(
			'Field'=>'theme',
			'Type'=>'char(255)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'from'=>array(
			'Field'=>'from',
			'Type'=>'char(255)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'to'=>array(
			'Field'=>'to',
			'Type'=>'char(255)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'newsletter' => array(
			'Field'	=>	'newsletter',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'date_add' => array(
			'Field'	=>	'date_add',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'content' => array(
			'Field'	=>	'content',
			'Type'	=> 	'text',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'',
			'Extra'	=>	'',
		),
		'encryption'=>array(
			'Field'=>'encryption',
			'Type'=>'char(20)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'recipients' => array(
			'Field'	=>	'recipients',
			'Type'	=> 	'text',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'',
			'Extra'	=>	'',
		),
		'send'=>array(
			'Field'=>'send',
			'Type'=>'tinyint(1)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'0',
			'Extra'=>'',
		),
	),
	'subscribe_subscribers'=>array(
		'id' => array(
			'Field'	=>	'id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'PRI',
			'Default'=>	'0',
			'Extra'	=>	'auto_increment',
		),
		'uin' => array(
			'Field'	=>	'uin',
			'Type'	=> 	'int(11)',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'newsletter' => array(
			'Field'	=>	'newsletter',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
	),
	'subscribe_usergroups_levels'=>array(
		'id' => array(
			'Field'	=>	'id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'PRI',
			'Default'=>	'0',
			'Extra'	=>	'auto_increment',
		),
		'newsletter_id' => array(
			'Field'	=>	'newsletter_id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'usergroup_id' => array(
			'Field'	=>	'usergroup_id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'level'=>array(
			'Field'=>'level',
			'Type'=>'tinyint(2)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'0',
			'Extra'=>'',
		),
	),
	'subscribe_users'=>array(
		'id' => array(
			'Field'	=>	'id',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'PRI',
			'Default'=>	'0',
			'Extra'	=>	'auto_increment',
		),
		'uin' => array(
			'Field'	=>	'uin',
			'Type'	=> 	'int(11)',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'active'=>array(
			'Field'=>'active',
			'Type'=>'tinyint(1)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'0',
			'Extra'=>'',
		),
		'date_add' => array(
			'Field'	=>	'date_add',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'date_active' => array(
			'Field'	=>	'date_active',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
		'email'=>array(
			'Field'=>'email',
			'Type'=>'char(255)',
			'Null'=>'NO',
			'Key'=>'',
			'Default'=>'',
			'Extra'=>'',
		),
		'format' => array(
			'Field'	=>	'format',
			'Type'	=> 	'int(11) unsigned',
			'Null'	=>	'NO',
			'Key'	=>	'',
			'Default'=>	'0',
			'Extra'	=>	'',
		),
	)
);
