<?php
/**
 * Файл обеспечивает генерацию структуры меню административого интерфейса главного модуля системы
 * @author blade39 <blade39@kolosstudio.ru>
 * @version 2.6.1
 */

$arMenu=array(
	'GLOBAL'=>array(
		'module'=>'main','href'=>'module=main','title'=>$this->GetText('menu_general'),'class'=>'other_poss','access'=>10,
		'items'=>array(
			"USERS"=>array(
				'module'=>'main','href'=>'module=main&amp;page=users','title'=>$this->GetText('menu_users'),'class'=>'user.png','access'=>9,
				'items'=>array(
					"ADD"=>array('module'=>'main','href'=>'module=main&amp;page=users&amp;action=new','title'=>$this->GetText('menu_users_add'),'class'=>'user_add.png','access'=>3),
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=users','title'=>$this->GetText('menu_users_list'),'class'=>'user.png','access'=>9),
				)
			),
			"USERGROUPS"=>array(
				'module'=>'main','href'=>'module=main&amp;page=usergroups','title'=>$this->GetText('menu_usergroups'),'class'=>'group.png','access'=>2,
				'items'=>array(
					"ADD"=>array('module'=>'main','href'=>'module=main&amp;page=usergroups&amp;action=new','title'=>$this->GetText('menu_usergroups_add'),'class'=>'group_add.png','access'=>3),
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=usergroups','title'=>$this->GetText('menu_usergroups_list'),'class'=>'group.png','access'=>9),
				)
			),
			"MODULES"=>array(
				'module'=>'main','href'=>'module=main&amp;page=modules','title'=>$this->GetText('menu_module_control'),'class'=>'bricks.png','access'=>0,
				'items'=>array(
					"ADD"=>array('module'=>'main','href'=>'module=main&amp;page=modules','title'=>$this->GetText('menu_modules_list'),'class'=>'brick.png','access'=>3),
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=modules#modules_list_1234567890_tab1','title'=>$this->GetText('menu_modules_install'),'class'=>'brick_add.png','access'=>9),
				)
			),
			"TEMPLATES"=>array(
				'module'=>'main','href'=>'module=main&amp;page=templates','title'=>$this->GetText('menu_templates'),'class'=>'page_paintbrush.png','access'=>7,
				'items'=>array(
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=templates','title'=>$this->GetText('menu_templates_list'),'class'=>'page_go.png','access'=>3),
					"INSTALL"=>array('module'=>'main','href'=>'module=main&amp;page=templates#modules_list_1234567890_tab1','title'=>$this->GetText('menu_templates_links'),'class'=>'page_gear.png','access'=>9),
				)
			),
			"ETEMPLATES"=>array('module'=>'main','href'=>'module=main&amp;page=eventtemplates','title'=>$this->GetText('menu_email_templates'),'class'=>'email_to_friend.png','access'=>6,
				'items'=>array(
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=eventtemplates','title'=>$this->GetText('menu_email_templates_list'),'class'=>'email_go.png','access'=>8),
				)
			),
			"FIELDS"=>array(
				'module'=>'main','href'=>'module=main&amp;page=fields','title'=>$this->GetText('menu_user_fields'),'class'=>'table_edit.png','access'=>8,
				'items'=>array(
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=fields','title'=>$this->GetText('menu_fields_list'),'class'=>'table_go.png','access'=>8),
					"ADD"=>array('module'=>'main','href'=>'module=main&amp;page=fields&amp;action=new','title'=>$this->GetText('menu_fields_add'),'class'=>'table_add.png','access'=>6),
				)
			),
			"EVENTS"=>array('module'=>'main','href'=>'module=main&amp;page=events','title'=>$this->GetText('menu_email_sended'),'class'=>'mail_box.png','access'=>0,
				'items'=>array(
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=events','title'=>$this->GetText('menu_email_sended_list'),'class'=>'mail_box.png','access'=>0),
				)
			),
			"OPTIONS"=>array(
				'module'=>'main','href'=>'module=main&amp;page=options','title'=>$this->GetText('menu_sys_config'),'class'=>'hammer.png','access'=>0,
				'items'=>array(
					"LIST"=>array('module'=>'main','href'=>'module=main&amp;page=options','title'=>$this->GetText('menu_sys_config'),'class'=>'hammer.png','access'=>0),
				)
			),
			"UPDATE"=>array('module'=>'main','href'=>'module=main&amp;page=update','title'=>$this->GetText('menu_update'),'class'=>'update.png','access'=>0),
			"GEOGRAPHY"=>array('module'=>'main','href'=>'module=main&amp;page=geography','title'=>$this->GetText('menu_geography'),'class'=>'globe_model.png','access'=>0),
		)
	)
);

